package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Aula generated by hbm2java
 */
public class Aula  implements java.io.Serializable {


     private int aulaCodigo;
     private Edificio edificio;
     private TipoAula tipoAula;
     private Carrera carrera;
     private String aulaNombre;
     private Integer aulaCapacidad;
     private String aulaDescripcion;
     private Set<Horario> horarios = new HashSet<Horario>(0);

    public Aula() {
    }

	
    public Aula(int aulaCodigo) {
        this.aulaCodigo = aulaCodigo;
    }
    public Aula(int aulaCodigo, Edificio edificio, TipoAula tipoAula, Carrera carrera, String aulaNombre, Integer aulaCapacidad, String aulaDescripcion, Set<Horario> horarios) {
       this.aulaCodigo = aulaCodigo;
       this.edificio = edificio;
       this.tipoAula = tipoAula;
       this.carrera = carrera;
       this.aulaNombre = aulaNombre;
       this.aulaCapacidad = aulaCapacidad;
       this.aulaDescripcion = aulaDescripcion;
       this.horarios = horarios;
    }
   
    public int getAulaCodigo() {
        return this.aulaCodigo;
    }
    
    public void setAulaCodigo(int aulaCodigo) {
        this.aulaCodigo = aulaCodigo;
    }
    public Edificio getEdificio() {
        return this.edificio;
    }
    
    public void setEdificio(Edificio edificio) {
        this.edificio = edificio;
    }
    public TipoAula getTipoAula() {
        return this.tipoAula;
    }
    
    public void setTipoAula(TipoAula tipoAula) {
        this.tipoAula = tipoAula;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public String getAulaNombre() {
        return this.aulaNombre;
    }
    
    public void setAulaNombre(String aulaNombre) {
        this.aulaNombre = aulaNombre;
    }
    public Integer getAulaCapacidad() {
        return this.aulaCapacidad;
    }
    
    public void setAulaCapacidad(Integer aulaCapacidad) {
        this.aulaCapacidad = aulaCapacidad;
    }
    public String getAulaDescripcion() {
        return this.aulaDescripcion;
    }
    
    public void setAulaDescripcion(String aulaDescripcion) {
        this.aulaDescripcion = aulaDescripcion;
    }
    public Set<Horario> getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Set<Horario> horarios) {
        this.horarios = horarios;
    }




}


