package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private int carrCodigo;
     private String carrNombre;
     private String carrDescripcion;
     private Set<Curso> cursos = new HashSet<Curso>(0);
     private Set<Aula> aulas = new HashSet<Aula>(0);
     private Set<MateriaSemestreCarrera> materiaSemestreCarreras = new HashSet<MateriaSemestreCarrera>(0);
     private Set<Estudiante> estudiantes = new HashSet<Estudiante>(0);

    public Carrera() {
    }

	
    public Carrera(int carrCodigo) {
        this.carrCodigo = carrCodigo;
    }
    public Carrera(int carrCodigo, String carrNombre, String carrDescripcion, Set<Curso> cursos, Set<Aula> aulas, Set<MateriaSemestreCarrera> materiaSemestreCarreras, Set<Estudiante> estudiantes) {
       this.carrCodigo = carrCodigo;
       this.carrNombre = carrNombre;
       this.carrDescripcion = carrDescripcion;
       this.cursos = cursos;
       this.aulas = aulas;
       this.materiaSemestreCarreras = materiaSemestreCarreras;
       this.estudiantes = estudiantes;
    }
   
    public int getCarrCodigo() {
        return this.carrCodigo;
    }
    
    public void setCarrCodigo(int carrCodigo) {
        this.carrCodigo = carrCodigo;
    }
    public String getCarrNombre() {
        return this.carrNombre;
    }
    
    public void setCarrNombre(String carrNombre) {
        this.carrNombre = carrNombre;
    }
    public String getCarrDescripcion() {
        return this.carrDescripcion;
    }
    
    public void setCarrDescripcion(String carrDescripcion) {
        this.carrDescripcion = carrDescripcion;
    }
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }
    public Set<Aula> getAulas() {
        return this.aulas;
    }
    
    public void setAulas(Set<Aula> aulas) {
        this.aulas = aulas;
    }
    public Set<MateriaSemestreCarrera> getMateriaSemestreCarreras() {
        return this.materiaSemestreCarreras;
    }
    
    public void setMateriaSemestreCarreras(Set<MateriaSemestreCarrera> materiaSemestreCarreras) {
        this.materiaSemestreCarreras = materiaSemestreCarreras;
    }
    public Set<Estudiante> getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set<Estudiante> estudiantes) {
        this.estudiantes = estudiantes;
    }




}


