package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private int cursCodigo;
     private Periodo periodo;
     private Carrera carrera;
     private Paralelo paralelo;
     private Semestre semestre;
     private String cursComentario;
     private Set<DocenteMateriaCurso> docenteMateriaCursos = new HashSet<DocenteMateriaCurso>(0);

    public Curso() {
    }

	
    public Curso(int cursCodigo) {
        this.cursCodigo = cursCodigo;
    }
    public Curso(int cursCodigo, Periodo periodo, Carrera carrera, Paralelo paralelo, Semestre semestre, String cursComentario, Set<DocenteMateriaCurso> docenteMateriaCursos) {
       this.cursCodigo = cursCodigo;
       this.periodo = periodo;
       this.carrera = carrera;
       this.paralelo = paralelo;
       this.semestre = semestre;
       this.cursComentario = cursComentario;
       this.docenteMateriaCursos = docenteMateriaCursos;
    }
   
    public int getCursCodigo() {
        return this.cursCodigo;
    }
    
    public void setCursCodigo(int cursCodigo) {
        this.cursCodigo = cursCodigo;
    }
    public Periodo getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Periodo periodo) {
        this.periodo = periodo;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public Paralelo getParalelo() {
        return this.paralelo;
    }
    
    public void setParalelo(Paralelo paralelo) {
        this.paralelo = paralelo;
    }
    public Semestre getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(Semestre semestre) {
        this.semestre = semestre;
    }
    public String getCursComentario() {
        return this.cursComentario;
    }
    
    public void setCursComentario(String cursComentario) {
        this.cursComentario = cursComentario;
    }
    public Set<DocenteMateriaCurso> getDocenteMateriaCursos() {
        return this.docenteMateriaCursos;
    }
    
    public void setDocenteMateriaCursos(Set<DocenteMateriaCurso> docenteMateriaCursos) {
        this.docenteMateriaCursos = docenteMateriaCursos;
    }




}


