package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Dedicacion generated by hbm2java
 */
public class Dedicacion  implements java.io.Serializable {


     private int dediCodigo;
     private String dediNombre;
     private String dediDescripcion;
     private Set<Docente> docentes = new HashSet<Docente>(0);

    public Dedicacion() {
    }

	
    public Dedicacion(int dediCodigo) {
        this.dediCodigo = dediCodigo;
    }
    public Dedicacion(int dediCodigo, String dediNombre, String dediDescripcion, Set<Docente> docentes) {
       this.dediCodigo = dediCodigo;
       this.dediNombre = dediNombre;
       this.dediDescripcion = dediDescripcion;
       this.docentes = docentes;
    }
   
    public int getDediCodigo() {
        return this.dediCodigo;
    }
    
    public void setDediCodigo(int dediCodigo) {
        this.dediCodigo = dediCodigo;
    }
    public String getDediNombre() {
        return this.dediNombre;
    }
    
    public void setDediNombre(String dediNombre) {
        this.dediNombre = dediNombre;
    }
    public String getDediDescripcion() {
        return this.dediDescripcion;
    }
    
    public void setDediDescripcion(String dediDescripcion) {
        this.dediDescripcion = dediDescripcion;
    }
    public Set<Docente> getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Set<Docente> docentes) {
        this.docentes = docentes;
    }




}


