package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * DisponibilidadHoras generated by hbm2java
 */
public class DisponibilidadHoras  implements java.io.Serializable {


     private int dihoCodigo;
     private Encuesta encuesta;
     private String dihoDia;
     private Date dihoHoraInicio;
     private Date dihoHoraFin;

    public DisponibilidadHoras() {
    }

	
    public DisponibilidadHoras(int dihoCodigo) {
        this.dihoCodigo = dihoCodigo;
    }
    public DisponibilidadHoras(int dihoCodigo, Encuesta encuesta, String dihoDia, Date dihoHoraInicio, Date dihoHoraFin) {
       this.dihoCodigo = dihoCodigo;
       this.encuesta = encuesta;
       this.dihoDia = dihoDia;
       this.dihoHoraInicio = dihoHoraInicio;
       this.dihoHoraFin = dihoHoraFin;
    }
   
    public int getDihoCodigo() {
        return this.dihoCodigo;
    }
    
    public void setDihoCodigo(int dihoCodigo) {
        this.dihoCodigo = dihoCodigo;
    }
    public Encuesta getEncuesta() {
        return this.encuesta;
    }
    
    public void setEncuesta(Encuesta encuesta) {
        this.encuesta = encuesta;
    }
    public String getDihoDia() {
        return this.dihoDia;
    }
    
    public void setDihoDia(String dihoDia) {
        this.dihoDia = dihoDia;
    }
    public Date getDihoHoraInicio() {
        return this.dihoHoraInicio;
    }
    
    public void setDihoHoraInicio(Date dihoHoraInicio) {
        this.dihoHoraInicio = dihoHoraInicio;
    }
    public Date getDihoHoraFin() {
        return this.dihoHoraFin;
    }
    
    public void setDihoHoraFin(Date dihoHoraFin) {
        this.dihoHoraFin = dihoHoraFin;
    }




}


