package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0



/**
 * DisponibilidadMateria generated by hbm2java
 */
public class DisponibilidadMateria  implements java.io.Serializable {


     private int dimaCodigo;
     private Encuesta encuesta;
     private Materia materia;

    public DisponibilidadMateria() {
    }

	
    public DisponibilidadMateria(int dimaCodigo) {
        this.dimaCodigo = dimaCodigo;
    }
    public DisponibilidadMateria(int dimaCodigo, Encuesta encuesta, Materia materia) {
       this.dimaCodigo = dimaCodigo;
       this.encuesta = encuesta;
       this.materia = materia;
    }
   
    public int getDimaCodigo() {
        return this.dimaCodigo;
    }
    
    public void setDimaCodigo(int dimaCodigo) {
        this.dimaCodigo = dimaCodigo;
    }
    public Encuesta getEncuesta() {
        return this.encuesta;
    }
    
    public void setEncuesta(Encuesta encuesta) {
        this.encuesta = encuesta;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }




}


