package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * DocenteMateriaCurso generated by hbm2java
 */
public class DocenteMateriaCurso  implements java.io.Serializable {


     private int domcCodigo;
     private Curso curso;
     private Docente docente;
     private Materia materia;
     private String domcComentario;
     private Set<Horario> horarios = new HashSet<Horario>(0);

    public DocenteMateriaCurso() {
    }

	
    public DocenteMateriaCurso(int domcCodigo) {
        this.domcCodigo = domcCodigo;
    }
    public DocenteMateriaCurso(int domcCodigo, Curso curso, Docente docente, Materia materia, String domcComentario, Set<Horario> horarios) {
       this.domcCodigo = domcCodigo;
       this.curso = curso;
       this.docente = docente;
       this.materia = materia;
       this.domcComentario = domcComentario;
       this.horarios = horarios;
    }
   
    public int getDomcCodigo() {
        return this.domcCodigo;
    }
    
    public void setDomcCodigo(int domcCodigo) {
        this.domcCodigo = domcCodigo;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public String getDomcComentario() {
        return this.domcComentario;
    }
    
    public void setDomcComentario(String domcComentario) {
        this.domcComentario = domcComentario;
    }
    public Set<Horario> getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Set<Horario> horarios) {
        this.horarios = horarios;
    }




}


