package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Docente generated by hbm2java
 */
public class Docente  implements java.io.Serializable {


     private int doceCodigo;
     private Dedicacion dedicacion;
     private TipoTrabajo tipoTrabajo;
     private String doceNombres;
     private String doceApellidos;
     private String doceCedula;
     private String doceEmailUce;
     private String doceEmailPersonal;
     private Date doceFechaNacimiento;
     private String doceGenero;
     private String doceTelefono;
     private String doceCelular;
     private String doceDireccion;
     private Set<DocenteMateriaCurso> docenteMateriaCursos = new HashSet<DocenteMateriaCurso>(0);
     private Set<Encuesta> encuestas = new HashSet<Encuesta>(0);

    public Docente() {
    }

	
    public Docente(int doceCodigo) {
        this.doceCodigo = doceCodigo;
    }
    public Docente(int doceCodigo, Dedicacion dedicacion, TipoTrabajo tipoTrabajo, String doceNombres, String doceApellidos, String doceCedula, String doceEmailUce, String doceEmailPersonal, Date doceFechaNacimiento, String doceGenero, String doceTelefono, String doceCelular, String doceDireccion, Set<DocenteMateriaCurso> docenteMateriaCursos, Set<Encuesta> encuestas) {
       this.doceCodigo = doceCodigo;
       this.dedicacion = dedicacion;
       this.tipoTrabajo = tipoTrabajo;
       this.doceNombres = doceNombres;
       this.doceApellidos = doceApellidos;
       this.doceCedula = doceCedula;
       this.doceEmailUce = doceEmailUce;
       this.doceEmailPersonal = doceEmailPersonal;
       this.doceFechaNacimiento = doceFechaNacimiento;
       this.doceGenero = doceGenero;
       this.doceTelefono = doceTelefono;
       this.doceCelular = doceCelular;
       this.doceDireccion = doceDireccion;
       this.docenteMateriaCursos = docenteMateriaCursos;
       this.encuestas = encuestas;
    }
   
    public int getDoceCodigo() {
        return this.doceCodigo;
    }
    
    public void setDoceCodigo(int doceCodigo) {
        this.doceCodigo = doceCodigo;
    }
    public Dedicacion getDedicacion() {
        return this.dedicacion;
    }
    
    public void setDedicacion(Dedicacion dedicacion) {
        this.dedicacion = dedicacion;
    }
    public TipoTrabajo getTipoTrabajo() {
        return this.tipoTrabajo;
    }
    
    public void setTipoTrabajo(TipoTrabajo tipoTrabajo) {
        this.tipoTrabajo = tipoTrabajo;
    }
    public String getDoceNombres() {
        return this.doceNombres;
    }
    
    public void setDoceNombres(String doceNombres) {
        this.doceNombres = doceNombres;
    }
    public String getDoceApellidos() {
        return this.doceApellidos;
    }
    
    public void setDoceApellidos(String doceApellidos) {
        this.doceApellidos = doceApellidos;
    }
    public String getDoceCedula() {
        return this.doceCedula;
    }
    
    public void setDoceCedula(String doceCedula) {
        this.doceCedula = doceCedula;
    }
    public String getDoceEmailUce() {
        return this.doceEmailUce;
    }
    
    public void setDoceEmailUce(String doceEmailUce) {
        this.doceEmailUce = doceEmailUce;
    }
    public String getDoceEmailPersonal() {
        return this.doceEmailPersonal;
    }
    
    public void setDoceEmailPersonal(String doceEmailPersonal) {
        this.doceEmailPersonal = doceEmailPersonal;
    }
    public Date getDoceFechaNacimiento() {
        return this.doceFechaNacimiento;
    }
    
    public void setDoceFechaNacimiento(Date doceFechaNacimiento) {
        this.doceFechaNacimiento = doceFechaNacimiento;
    }
    public String getDoceGenero() {
        return this.doceGenero;
    }
    
    public void setDoceGenero(String doceGenero) {
        this.doceGenero = doceGenero;
    }
    public String getDoceTelefono() {
        return this.doceTelefono;
    }
    
    public void setDoceTelefono(String doceTelefono) {
        this.doceTelefono = doceTelefono;
    }
    public String getDoceCelular() {
        return this.doceCelular;
    }
    
    public void setDoceCelular(String doceCelular) {
        this.doceCelular = doceCelular;
    }
    public String getDoceDireccion() {
        return this.doceDireccion;
    }
    
    public void setDoceDireccion(String doceDireccion) {
        this.doceDireccion = doceDireccion;
    }
    public Set<DocenteMateriaCurso> getDocenteMateriaCursos() {
        return this.docenteMateriaCursos;
    }
    
    public void setDocenteMateriaCursos(Set<DocenteMateriaCurso> docenteMateriaCursos) {
        this.docenteMateriaCursos = docenteMateriaCursos;
    }
    public Set<Encuesta> getEncuestas() {
        return this.encuestas;
    }
    
    public void setEncuestas(Set<Encuesta> encuestas) {
        this.encuestas = encuestas;
    }




}


