package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Edificio generated by hbm2java
 */
public class Edificio  implements java.io.Serializable {


     private int edifCodigo;
     private String edifNombre;
     private String edifDescripcion;
     private Set<Aula> aulas = new HashSet<Aula>(0);

    public Edificio() {
    }

	
    public Edificio(int edifCodigo) {
        this.edifCodigo = edifCodigo;
    }
    public Edificio(int edifCodigo, String edifNombre, String edifDescripcion, Set<Aula> aulas) {
       this.edifCodigo = edifCodigo;
       this.edifNombre = edifNombre;
       this.edifDescripcion = edifDescripcion;
       this.aulas = aulas;
    }
   
    public int getEdifCodigo() {
        return this.edifCodigo;
    }
    
    public void setEdifCodigo(int edifCodigo) {
        this.edifCodigo = edifCodigo;
    }
    public String getEdifNombre() {
        return this.edifNombre;
    }
    
    public void setEdifNombre(String edifNombre) {
        this.edifNombre = edifNombre;
    }
    public String getEdifDescripcion() {
        return this.edifDescripcion;
    }
    
    public void setEdifDescripcion(String edifDescripcion) {
        this.edifDescripcion = edifDescripcion;
    }
    public Set<Aula> getAulas() {
        return this.aulas;
    }
    
    public void setAulas(Set<Aula> aulas) {
        this.aulas = aulas;
    }




}


