package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Encuesta generated by hbm2java
 */
public class Encuesta  implements java.io.Serializable {


     private int encuCodigo;
     private Docente docente;
     private Periodo periodo;
     private String encuComentario;
     private Set<DisponibilidadHoras> disponibilidadHorases = new HashSet<DisponibilidadHoras>(0);
     private Set<DisponibilidadMateria> disponibilidadMaterias = new HashSet<DisponibilidadMateria>(0);

    public Encuesta() {
    }

	
    public Encuesta(int encuCodigo) {
        this.encuCodigo = encuCodigo;
    }
    public Encuesta(int encuCodigo, Docente docente, Periodo periodo, String encuComentario, Set<DisponibilidadHoras> disponibilidadHorases, Set<DisponibilidadMateria> disponibilidadMaterias) {
       this.encuCodigo = encuCodigo;
       this.docente = docente;
       this.periodo = periodo;
       this.encuComentario = encuComentario;
       this.disponibilidadHorases = disponibilidadHorases;
       this.disponibilidadMaterias = disponibilidadMaterias;
    }
   
    public int getEncuCodigo() {
        return this.encuCodigo;
    }
    
    public void setEncuCodigo(int encuCodigo) {
        this.encuCodigo = encuCodigo;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Periodo getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Periodo periodo) {
        this.periodo = periodo;
    }
    public String getEncuComentario() {
        return this.encuComentario;
    }
    
    public void setEncuComentario(String encuComentario) {
        this.encuComentario = encuComentario;
    }
    public Set<DisponibilidadHoras> getDisponibilidadHorases() {
        return this.disponibilidadHorases;
    }
    
    public void setDisponibilidadHorases(Set<DisponibilidadHoras> disponibilidadHorases) {
        this.disponibilidadHorases = disponibilidadHorases;
    }
    public Set<DisponibilidadMateria> getDisponibilidadMaterias() {
        return this.disponibilidadMaterias;
    }
    
    public void setDisponibilidadMaterias(Set<DisponibilidadMateria> disponibilidadMaterias) {
        this.disponibilidadMaterias = disponibilidadMaterias;
    }




}


