package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private int horaCodigo;
     private Aula aula;
     private DocenteMateriaCurso docenteMateriaCurso;
     private String horaDia;
     private Date horaInicio;
     private Date horaFin;

    public Horario() {
    }

	
    public Horario(int horaCodigo) {
        this.horaCodigo = horaCodigo;
    }
    public Horario(int horaCodigo, Aula aula, DocenteMateriaCurso docenteMateriaCurso, String horaDia, Date horaInicio, Date horaFin) {
       this.horaCodigo = horaCodigo;
       this.aula = aula;
       this.docenteMateriaCurso = docenteMateriaCurso;
       this.horaDia = horaDia;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
    }
   
    public int getHoraCodigo() {
        return this.horaCodigo;
    }
    
    public void setHoraCodigo(int horaCodigo) {
        this.horaCodigo = horaCodigo;
    }
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }
    public DocenteMateriaCurso getDocenteMateriaCurso() {
        return this.docenteMateriaCurso;
    }
    
    public void setDocenteMateriaCurso(DocenteMateriaCurso docenteMateriaCurso) {
        this.docenteMateriaCurso = docenteMateriaCurso;
    }
    public String getHoraDia() {
        return this.horaDia;
    }
    
    public void setHoraDia(String horaDia) {
        this.horaDia = horaDia;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }




}


