package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0



/**
 * MateriaEstadistico generated by hbm2java
 */
public class MateriaEstadistico  implements java.io.Serializable {


     private int maesCodigo;
     private Periodo periodo;
     private Materia materia;
     private String maesDescripcion;

    public MateriaEstadistico() {
    }

	
    public MateriaEstadistico(int maesCodigo) {
        this.maesCodigo = maesCodigo;
    }
    public MateriaEstadistico(int maesCodigo, Periodo periodo, Materia materia, String maesDescripcion) {
       this.maesCodigo = maesCodigo;
       this.periodo = periodo;
       this.materia = materia;
       this.maesDescripcion = maesDescripcion;
    }
   
    public int getMaesCodigo() {
        return this.maesCodigo;
    }
    
    public void setMaesCodigo(int maesCodigo) {
        this.maesCodigo = maesCodigo;
    }
    public Periodo getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Periodo periodo) {
        this.periodo = periodo;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public String getMaesDescripcion() {
        return this.maesDescripcion;
    }
    
    public void setMaesDescripcion(String maesDescripcion) {
        this.maesDescripcion = maesDescripcion;
    }




}


