package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private int mateCodigo;
     private String mateNombre;
     private Integer mateCreditos;
     private String mateDescripcion;
     private Set<DisponibilidadMateria> disponibilidadMaterias = new HashSet<DisponibilidadMateria>(0);
     private Set<MateriaSemestreCarrera> materiaSemestreCarreras = new HashSet<MateriaSemestreCarrera>(0);
     private Set<DocenteMateriaCurso> docenteMateriaCursos = new HashSet<DocenteMateriaCurso>(0);
     private Set<Preinscripcion> preinscripcions = new HashSet<Preinscripcion>(0);
     private Set<MateriaEstadistico> materiaEstadisticos = new HashSet<MateriaEstadistico>(0);

    public Materia() {
    }

	
    public Materia(int mateCodigo) {
        this.mateCodigo = mateCodigo;
    }
    public Materia(int mateCodigo, String mateNombre, Integer mateCreditos, String mateDescripcion, Set<DisponibilidadMateria> disponibilidadMaterias, Set<MateriaSemestreCarrera> materiaSemestreCarreras, Set<DocenteMateriaCurso> docenteMateriaCursos, Set<Preinscripcion> preinscripcions, Set<MateriaEstadistico> materiaEstadisticos) {
       this.mateCodigo = mateCodigo;
       this.mateNombre = mateNombre;
       this.mateCreditos = mateCreditos;
       this.mateDescripcion = mateDescripcion;
       this.disponibilidadMaterias = disponibilidadMaterias;
       this.materiaSemestreCarreras = materiaSemestreCarreras;
       this.docenteMateriaCursos = docenteMateriaCursos;
       this.preinscripcions = preinscripcions;
       this.materiaEstadisticos = materiaEstadisticos;
    }
   
    public int getMateCodigo() {
        return this.mateCodigo;
    }
    
    public void setMateCodigo(int mateCodigo) {
        this.mateCodigo = mateCodigo;
    }
    public String getMateNombre() {
        return this.mateNombre;
    }
    
    public void setMateNombre(String mateNombre) {
        this.mateNombre = mateNombre;
    }
    public Integer getMateCreditos() {
        return this.mateCreditos;
    }
    
    public void setMateCreditos(Integer mateCreditos) {
        this.mateCreditos = mateCreditos;
    }
    public String getMateDescripcion() {
        return this.mateDescripcion;
    }
    
    public void setMateDescripcion(String mateDescripcion) {
        this.mateDescripcion = mateDescripcion;
    }
    public Set<DisponibilidadMateria> getDisponibilidadMaterias() {
        return this.disponibilidadMaterias;
    }
    
    public void setDisponibilidadMaterias(Set<DisponibilidadMateria> disponibilidadMaterias) {
        this.disponibilidadMaterias = disponibilidadMaterias;
    }
    public Set<MateriaSemestreCarrera> getMateriaSemestreCarreras() {
        return this.materiaSemestreCarreras;
    }
    
    public void setMateriaSemestreCarreras(Set<MateriaSemestreCarrera> materiaSemestreCarreras) {
        this.materiaSemestreCarreras = materiaSemestreCarreras;
    }
    public Set<DocenteMateriaCurso> getDocenteMateriaCursos() {
        return this.docenteMateriaCursos;
    }
    
    public void setDocenteMateriaCursos(Set<DocenteMateriaCurso> docenteMateriaCursos) {
        this.docenteMateriaCursos = docenteMateriaCursos;
    }
    public Set<Preinscripcion> getPreinscripcions() {
        return this.preinscripcions;
    }
    
    public void setPreinscripcions(Set<Preinscripcion> preinscripcions) {
        this.preinscripcions = preinscripcions;
    }
    public Set<MateriaEstadistico> getMateriaEstadisticos() {
        return this.materiaEstadisticos;
    }
    
    public void setMateriaEstadisticos(Set<MateriaEstadistico> materiaEstadisticos) {
        this.materiaEstadisticos = materiaEstadisticos;
    }




}


