package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0



/**
 * MateriaSemestreCarrera generated by hbm2java
 */
public class MateriaSemestreCarrera  implements java.io.Serializable {


     private int mascCodigo;
     private Materia materia;
     private Carrera carrera;
     private Semestre semestre;
     private String mascDescripcion;

    public MateriaSemestreCarrera() {
    }

	
    public MateriaSemestreCarrera(int mascCodigo) {
        this.mascCodigo = mascCodigo;
    }
    public MateriaSemestreCarrera(int mascCodigo, Materia materia, Carrera carrera, Semestre semestre, String mascDescripcion) {
       this.mascCodigo = mascCodigo;
       this.materia = materia;
       this.carrera = carrera;
       this.semestre = semestre;
       this.mascDescripcion = mascDescripcion;
    }
   
    public int getMascCodigo() {
        return this.mascCodigo;
    }
    
    public void setMascCodigo(int mascCodigo) {
        this.mascCodigo = mascCodigo;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public Semestre getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(Semestre semestre) {
        this.semestre = semestre;
    }
    public String getMascDescripcion() {
        return this.mascDescripcion;
    }
    
    public void setMascDescripcion(String mascDescripcion) {
        this.mascDescripcion = mascDescripcion;
    }




}


