package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private int menuCodigo;
     private Integer menuPadre;
     private Integer menuNivel;
     private Integer menuOrden;
     private String menuNombre;
     private String menuUrl;
     private String menuIcono;
     private Integer menuEstado;
     private Set<RolMenu> rolMenus = new HashSet<RolMenu>(0);

    public Menu() {
    }

	
    public Menu(int menuCodigo) {
        this.menuCodigo = menuCodigo;
    }
    public Menu(int menuCodigo, Integer menuPadre, Integer menuNivel, Integer menuOrden, String menuNombre, String menuUrl, String menuIcono, Integer menuEstado, Set<RolMenu> rolMenus) {
       this.menuCodigo = menuCodigo;
       this.menuPadre = menuPadre;
       this.menuNivel = menuNivel;
       this.menuOrden = menuOrden;
       this.menuNombre = menuNombre;
       this.menuUrl = menuUrl;
       this.menuIcono = menuIcono;
       this.menuEstado = menuEstado;
       this.rolMenus = rolMenus;
    }
   
    public int getMenuCodigo() {
        return this.menuCodigo;
    }
    
    public void setMenuCodigo(int menuCodigo) {
        this.menuCodigo = menuCodigo;
    }
    public Integer getMenuPadre() {
        return this.menuPadre;
    }
    
    public void setMenuPadre(Integer menuPadre) {
        this.menuPadre = menuPadre;
    }
    public Integer getMenuNivel() {
        return this.menuNivel;
    }
    
    public void setMenuNivel(Integer menuNivel) {
        this.menuNivel = menuNivel;
    }
    public Integer getMenuOrden() {
        return this.menuOrden;
    }
    
    public void setMenuOrden(Integer menuOrden) {
        this.menuOrden = menuOrden;
    }
    public String getMenuNombre() {
        return this.menuNombre;
    }
    
    public void setMenuNombre(String menuNombre) {
        this.menuNombre = menuNombre;
    }
    public String getMenuUrl() {
        return this.menuUrl;
    }
    
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }
    public String getMenuIcono() {
        return this.menuIcono;
    }
    
    public void setMenuIcono(String menuIcono) {
        this.menuIcono = menuIcono;
    }
    public Integer getMenuEstado() {
        return this.menuEstado;
    }
    
    public void setMenuEstado(Integer menuEstado) {
        this.menuEstado = menuEstado;
    }
    public Set<RolMenu> getRolMenus() {
        return this.rolMenus;
    }
    
    public void setRolMenus(Set<RolMenu> rolMenus) {
        this.rolMenus = rolMenus;
    }




}


