package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Paralelo generated by hbm2java
 */
public class Paralelo  implements java.io.Serializable {


     private int paraCodigo;
     private String paraNombre;
     private String paraDescripcion;
     private Set<Curso> cursos = new HashSet<Curso>(0);

    public Paralelo() {
    }

	
    public Paralelo(int paraCodigo) {
        this.paraCodigo = paraCodigo;
    }
    public Paralelo(int paraCodigo, String paraNombre, String paraDescripcion, Set<Curso> cursos) {
       this.paraCodigo = paraCodigo;
       this.paraNombre = paraNombre;
       this.paraDescripcion = paraDescripcion;
       this.cursos = cursos;
    }
   
    public int getParaCodigo() {
        return this.paraCodigo;
    }
    
    public void setParaCodigo(int paraCodigo) {
        this.paraCodigo = paraCodigo;
    }
    public String getParaNombre() {
        return this.paraNombre;
    }
    
    public void setParaNombre(String paraNombre) {
        this.paraNombre = paraNombre;
    }
    public String getParaDescripcion() {
        return this.paraDescripcion;
    }
    
    public void setParaDescripcion(String paraDescripcion) {
        this.paraDescripcion = paraDescripcion;
    }
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }




}


