package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0



/**
 * Preinscripcion generated by hbm2java
 */
public class Preinscripcion  implements java.io.Serializable {


     private int preiCodigo;
     private Periodo periodo;
     private Materia materia;
     private Estudiante estudiante;

    public Preinscripcion() {
    }

	
    public Preinscripcion(int preiCodigo) {
        this.preiCodigo = preiCodigo;
    }
    public Preinscripcion(int preiCodigo, Periodo periodo, Materia materia, Estudiante estudiante) {
       this.preiCodigo = preiCodigo;
       this.periodo = periodo;
       this.materia = materia;
       this.estudiante = estudiante;
    }
   
    public int getPreiCodigo() {
        return this.preiCodigo;
    }
    
    public void setPreiCodigo(int preiCodigo) {
        this.preiCodigo = preiCodigo;
    }
    public Periodo getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Periodo periodo) {
        this.periodo = periodo;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }




}


