package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private int rolCodigo;
     private String rolNombre;
     private String rolDescripcion;
     private Integer rolEstado;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<RolMenu> rolMenus = new HashSet<RolMenu>(0);

    public Rol() {
    }

	
    public Rol(int rolCodigo) {
        this.rolCodigo = rolCodigo;
    }
    public Rol(int rolCodigo, String rolNombre, String rolDescripcion, Integer rolEstado, Set<Usuario> usuarios, Set<RolMenu> rolMenus) {
       this.rolCodigo = rolCodigo;
       this.rolNombre = rolNombre;
       this.rolDescripcion = rolDescripcion;
       this.rolEstado = rolEstado;
       this.usuarios = usuarios;
       this.rolMenus = rolMenus;
    }
   
    public int getRolCodigo() {
        return this.rolCodigo;
    }
    
    public void setRolCodigo(int rolCodigo) {
        this.rolCodigo = rolCodigo;
    }
    public String getRolNombre() {
        return this.rolNombre;
    }
    
    public void setRolNombre(String rolNombre) {
        this.rolNombre = rolNombre;
    }
    public String getRolDescripcion() {
        return this.rolDescripcion;
    }
    
    public void setRolDescripcion(String rolDescripcion) {
        this.rolDescripcion = rolDescripcion;
    }
    public Integer getRolEstado() {
        return this.rolEstado;
    }
    
    public void setRolEstado(Integer rolEstado) {
        this.rolEstado = rolEstado;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<RolMenu> getRolMenus() {
        return this.rolMenus;
    }
    
    public void setRolMenus(Set<RolMenu> rolMenus) {
        this.rolMenus = rolMenus;
    }




}


