package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0



/**
 * RolMenu generated by hbm2java
 */
public class RolMenu  implements java.io.Serializable {


     private int romeCodigo;
     private Rol rol;
     private Menu menu;

    public RolMenu() {
    }

	
    public RolMenu(int romeCodigo) {
        this.romeCodigo = romeCodigo;
    }
    public RolMenu(int romeCodigo, Rol rol, Menu menu) {
       this.romeCodigo = romeCodigo;
       this.rol = rol;
       this.menu = menu;
    }
   
    public int getRomeCodigo() {
        return this.romeCodigo;
    }
    
    public void setRomeCodigo(int romeCodigo) {
        this.romeCodigo = romeCodigo;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }




}


