package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Semestre generated by hbm2java
 */
public class Semestre  implements java.io.Serializable {


     private int semeCodigo;
     private String semeNombre;
     private String semeDescripcion;
     private Set<Curso> cursos = new HashSet<Curso>(0);
     private Set<MateriaSemestreCarrera> materiaSemestreCarreras = new HashSet<MateriaSemestreCarrera>(0);

    public Semestre() {
    }

	
    public Semestre(int semeCodigo) {
        this.semeCodigo = semeCodigo;
    }
    public Semestre(int semeCodigo, String semeNombre, String semeDescripcion, Set<Curso> cursos, Set<MateriaSemestreCarrera> materiaSemestreCarreras) {
       this.semeCodigo = semeCodigo;
       this.semeNombre = semeNombre;
       this.semeDescripcion = semeDescripcion;
       this.cursos = cursos;
       this.materiaSemestreCarreras = materiaSemestreCarreras;
    }
   
    public int getSemeCodigo() {
        return this.semeCodigo;
    }
    
    public void setSemeCodigo(int semeCodigo) {
        this.semeCodigo = semeCodigo;
    }
    public String getSemeNombre() {
        return this.semeNombre;
    }
    
    public void setSemeNombre(String semeNombre) {
        this.semeNombre = semeNombre;
    }
    public String getSemeDescripcion() {
        return this.semeDescripcion;
    }
    
    public void setSemeDescripcion(String semeDescripcion) {
        this.semeDescripcion = semeDescripcion;
    }
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }
    public Set<MateriaSemestreCarrera> getMateriaSemestreCarreras() {
        return this.materiaSemestreCarreras;
    }
    
    public void setMateriaSemestreCarreras(Set<MateriaSemestreCarrera> materiaSemestreCarreras) {
        this.materiaSemestreCarreras = materiaSemestreCarreras;
    }




}


