package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TipoTrabajo generated by hbm2java
 */
public class TipoTrabajo  implements java.io.Serializable {


     private int titrCodigo;
     private String titrNombre;
     private String titrDescripcion;
     private Set<Docente> docentes = new HashSet<Docente>(0);

    public TipoTrabajo() {
    }

	
    public TipoTrabajo(int titrCodigo) {
        this.titrCodigo = titrCodigo;
    }
    public TipoTrabajo(int titrCodigo, String titrNombre, String titrDescripcion, Set<Docente> docentes) {
       this.titrCodigo = titrCodigo;
       this.titrNombre = titrNombre;
       this.titrDescripcion = titrDescripcion;
       this.docentes = docentes;
    }
   
    public int getTitrCodigo() {
        return this.titrCodigo;
    }
    
    public void setTitrCodigo(int titrCodigo) {
        this.titrCodigo = titrCodigo;
    }
    public String getTitrNombre() {
        return this.titrNombre;
    }
    
    public void setTitrNombre(String titrNombre) {
        this.titrNombre = titrNombre;
    }
    public String getTitrDescripcion() {
        return this.titrDescripcion;
    }
    
    public void setTitrDescripcion(String titrDescripcion) {
        this.titrDescripcion = titrDescripcion;
    }
    public Set<Docente> getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Set<Docente> docentes) {
        this.docentes = docentes;
    }




}


