package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TipoAula generated by hbm2java
 */
public class TipoAula  implements java.io.Serializable {


     private int tiauCodigo;
     private String tiauNombre;
     private String tiauDescripcion;
     private Set<Aula> aulas = new HashSet<Aula>(0);

    public TipoAula() {
    }

	
    public TipoAula(int tiauCodigo) {
        this.tiauCodigo = tiauCodigo;
    }
    public TipoAula(int tiauCodigo, String tiauNombre, String tiauDescripcion, Set<Aula> aulas) {
       this.tiauCodigo = tiauCodigo;
       this.tiauNombre = tiauNombre;
       this.tiauDescripcion = tiauDescripcion;
       this.aulas = aulas;
    }
   
    public int getTiauCodigo() {
        return this.tiauCodigo;
    }
    
    public void setTiauCodigo(int tiauCodigo) {
        this.tiauCodigo = tiauCodigo;
    }
    public String getTiauNombre() {
        return this.tiauNombre;
    }
    
    public void setTiauNombre(String tiauNombre) {
        this.tiauNombre = tiauNombre;
    }
    public String getTiauDescripcion() {
        return this.tiauDescripcion;
    }
    
    public void setTiauDescripcion(String tiauDescripcion) {
        this.tiauDescripcion = tiauDescripcion;
    }
    public Set<Aula> getAulas() {
        return this.aulas;
    }
    
    public void setAulas(Set<Aula> aulas) {
        this.aulas = aulas;
    }




}


