package model;
// Generated 01-feb-2016 18:02:31 by Hibernate Tools 3.6.0



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int userCodigo;
     private Rol rol;
     private String userNombre;
     private String userNombreCompleto;
     private String userPassword;
     private Integer userEstado;

    public Usuario() {
        rol = new Rol();
    }

	
    public Usuario(int userCodigo) {
        this.userCodigo = userCodigo;
    }
    public Usuario(int userCodigo, Rol rol, String userNombre, String userNombreCompleto, String userPassword, Integer userEstado) {
       this.userCodigo = userCodigo;
       this.rol = rol;
       this.userNombre = userNombre;
       this.userNombreCompleto = userNombreCompleto;
       this.userPassword = userPassword;
       this.userEstado = userEstado;
    }
   
    public int getUserCodigo() {
        return this.userCodigo;
    }
    
    public void setUserCodigo(int userCodigo) {
        this.userCodigo = userCodigo;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getUserNombre() {
        return this.userNombre;
    }
    
    public void setUserNombre(String userNombre) {
        this.userNombre = userNombre;
    }
    public String getUserNombreCompleto() {
        return this.userNombreCompleto;
    }
    
    public void setUserNombreCompleto(String userNombreCompleto) {
        this.userNombreCompleto = userNombreCompleto;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public Integer getUserEstado() {
        return this.userEstado;
    }
    
    public void setUserEstado(Integer userEstado) {
        this.userEstado = userEstado;
    }




}


